In [2]:
import numpy as np
my_arr = np.arange(1000000)

In [3]:
%time for _ in range(10): my_arr = my_arr *2

Wall time: 28.1 ms


In [4]:
# Generate some random data
data = np.random.randn(2,3)
data

array([[ 0.90344795, -0.35287774, -1.05102536],
       [-0.53374345, -0.295893  , -1.3780091 ]])

In [5]:
data * 10

array([[  9.03447953,  -3.52877743, -10.51025365],
       [ -5.33743453,  -2.95893002, -13.78009103]])

In [6]:
data + data

array([[ 1.80689591, -0.70575549, -2.10205073],
       [-1.06748691, -0.591786  , -2.75601821]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
print(arr1)

[6.  7.5 8.  0.  1. ]


In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [15]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# it's not save to think the empty will create zero array
np.empty((2, 3))

array([[1.80689591, 0.70575549, 2.10205073],
       [1.06748691, 0.591786  , 2.75601821]])

In [21]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [26]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[0 0 0 0]
 [0 0 0 0]]


In [29]:
print(1 / arr)
print(arr ** 5)

[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]]
[[    1    32   243  1024]
 [ 3125  7776 16807 32768]]


In [30]:
arr2 = np.array([[2, 1, 4, 3], [8, 6, 5, 7]])
print(arr2)

[[2 1 4 3]
 [8 6 5 7]]


In [31]:
print(arr2 > arr)

[[ True False  True False]
 [ True False False False]]


In [32]:
import numpy as np
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])

In [33]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [34]:
b

array([1, 2, 3])

In [35]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [36]:
arr = np.arange(10)

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
% arr第6个元素
arr[5]

5

In [39]:
% left close right open
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [42]:
arr_slice[1] =12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
arr[:] = 64

In [45]:
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [47]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2d = np.random.randn(3, 3)

In [49]:
arr2d

array([[ 2.16557174e+00, -5.33325535e-01,  9.27150114e-04],
       [-1.53687999e-01, -3.15699219e-01, -5.51348059e-01],
       [ 6.18842941e-01,  3.28927666e-01, -5.55822216e-01]])

In [50]:
arr2d[2]

array([ 0.61884294,  0.32892767, -0.55582222])

In [51]:
arr2d[0][2]

0.0009271501144490785

In [52]:
arr2d[0, 2]

0.0009271501144490785

In [53]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [54]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr3d[0, 0, 2]

3

In [59]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
print('=====================')
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [60]:
print(arr)

[64 64 64 64 64 64 64 64 64 64]


In [61]:
arr[1:6]

array([64, 64, 64, 64, 64])

In [62]:
arr2d

array([[ 2.16557174e+00, -5.33325535e-01,  9.27150114e-04],
       [-1.53687999e-01, -3.15699219e-01, -5.51348059e-01],
       [ 6.18842941e-01,  3.28927666e-01, -5.55822216e-01]])

In [63]:
arr2d[:2]

array([[ 2.16557174e+00, -5.33325535e-01,  9.27150114e-04],
       [-1.53687999e-01, -3.15699219e-01, -5.51348059e-01]])

In [64]:
arr2d[:2, 1:]

array([[-0.53332554,  0.00092715],
       [-0.31569922, -0.55134806]])

In [65]:
arr2d[1, :2]

array([-0.153688  , -0.31569922])

In [67]:
arr2d[:2, 2]

array([ 0.00092715, -0.55134806])

In [68]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.26523849 -1.56415513 -0.85047222  0.99333973]
 [ 0.06758897 -1.05501646 -0.1127671   0.35003187]
 [-0.19778374 -0.3124793   0.41534097  2.28001291]
 [ 0.31076837  1.34718041 -0.94247645  1.04191074]
 [-0.7702541   0.67544008  0.78919664  0.74805171]
 [-0.57473604 -1.48037489 -1.09279906  0.44678837]
 [-1.15394923  0.84716603 -0.03474545 -1.80780033]]


In [70]:
print(names == 'Bob')

[ True False False  True False False False]


In [71]:
print(data[names == 'Bob'])

[[-1.26523849 -1.56415513 -0.85047222  0.99333973]
 [ 0.31076837  1.34718041 -0.94247645  1.04191074]]


In [72]:
print(data[names == 'Bob', 2:])

[[-0.85047222  0.99333973]
 [-0.94247645  1.04191074]]


In [73]:
print(data[names == 'Bob', 3:])

[[0.99333973]
 [1.04191074]]


In [75]:
print(names != 'Bob')

[False  True  True False  True  True  True]


In [76]:
print(data[~(names == 'Bob')])

[[ 0.06758897 -1.05501646 -0.1127671   0.35003187]
 [-0.19778374 -0.3124793   0.41534097  2.28001291]
 [-0.7702541   0.67544008  0.78919664  0.74805171]
 [-0.57473604 -1.48037489 -1.09279906  0.44678837]
 [-1.15394923  0.84716603 -0.03474545 -1.80780033]]


In [81]:
cond = names == 'Bob'

In [82]:
cond

array([ True, False, False,  True, False, False, False])

In [83]:
print(data[~cond])

[[ 0.06758897 -1.05501646 -0.1127671   0.35003187]
 [-0.19778374 -0.3124793   0.41534097  2.28001291]
 [-0.7702541   0.67544008  0.78919664  0.74805171]
 [-0.57473604 -1.48037489 -1.09279906  0.44678837]
 [-1.15394923  0.84716603 -0.03474545 -1.80780033]]


In [84]:
mask = (names == 'Bob') | (names == 'Will')
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[-1.26523849 -1.56415513 -0.85047222  0.99333973]
 [-0.19778374 -0.3124793   0.41534097  2.28001291]
 [ 0.31076837  1.34718041 -0.94247645  1.04191074]
 [-0.7702541   0.67544008  0.78919664  0.74805171]]


In [85]:
data[data < 0] = 0
print(data)

[[0.         0.         0.         0.99333973]
 [0.06758897 0.         0.         0.35003187]
 [0.         0.         0.41534097 2.28001291]
 [0.31076837 1.34718041 0.         1.04191074]
 [0.         0.67544008 0.78919664 0.74805171]
 [0.         0.         0.         0.44678837]
 [0.         0.84716603 0.         0.        ]]


In [86]:
data[names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.06758897 0.         0.         0.35003187]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.         0.         0.44678837]
 [0.         0.84716603 0.         0.        ]]


In [87]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [89]:
print(arr[[4, 3, 0, 6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [90]:
print(arr[[-3, -5, -7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [91]:
arr = np.arange(32).reshape((8, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [92]:
print(arr[[1, 5, 7, 2],[0, 0, 0, 0]])

[ 4 20 28  8]


In [94]:
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [5]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [6]:
arr = np.random.randn(6, 3)

In [7]:
print(arr)
print (np.dot(arr.T, arr))

[[-0.77209616  0.0764247   0.83156353]
 [ 0.17172537  1.00032569  1.48981348]
 [-0.60640387 -0.25837734  1.07688931]
 [ 0.24460346  0.80009498  0.01367579]
 [-1.68433266 -1.28633008  2.41412173]
 [ 1.27553194 -0.21888406 -0.47324197]]
[[ 5.51713682  2.35257527 -5.70571224]
 [ 2.35257527  3.41595837 -1.71522346]
 [-5.70571224 -1.71522346 10.1228614 ]]
