In [1]:
import numpy as np

an_array = np.array([3, 33, 333])

print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(3,)


In [3]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
an_array[0] = 888
print(an_array)

[888  33 333]


In [7]:
an_array[0] = 'hi'
print(an_array)

ValueError: invalid literal for int() with base 10: 'hi'

In [5]:
str_array = np.array(['3', '33', '333'])
print(str_array)

['3' '33' '333']


In [6]:
str_array[0] = 888
str_array

array(['888', '33', '333'], dtype='<U3')

In [10]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)
print('The shape is 2 rows, 3 columns: ', another.shape)
print('Accessing elements [0,0], [0,1], and [1,0] of the ndarray:', another[0, 0], another[0, 1], another[1, 0]) 

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray: 11 12 21


In [11]:
import numpy as np

ex1 = np.zeros((2, 2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [13]:
ex2 = np.full((2, 2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [15]:
ex3 = np.eye(3, 3)
print(ex3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
ex4 = np.ones((4, 3))
print(ex4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
print(ex4.shape)

(4, 3)


In [20]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.12821432 0.16586347]
 [0.15010423 0.05285902]]
