In [1]:
import numpy as np

an_array = np.array([3, 33, 333])

print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(3,)


In [3]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
an_array[0] = 888
print(an_array)

[888  33 333]


In [7]:
an_array[0] = 'hi'
print(an_array)

ValueError: invalid literal for int() with base 10: 'hi'

In [5]:
str_array = np.array(['3', '33', '333'])
print(str_array)

['3' '33' '333']


In [6]:
str_array[0] = 888
str_array

array(['888', '33', '333'], dtype='<U3')

In [10]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)
print('The shape is 2 rows, 3 columns: ', another.shape)
print('Accessing elements [0,0], [0,1], and [1,0] of the ndarray:', another[0, 0], another[0, 1], another[1, 0]) 

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray: 11 12 21


In [11]:
import numpy as np

ex1 = np.zeros((2, 2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [13]:
ex2 = np.full((2, 2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [15]:
ex3 = np.eye(3, 3)
print(ex3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
ex4 = np.ones((4, 3))
print(ex4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
print(ex4.shape)

(4, 3)


In [20]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.12821432 0.16586347]
 [0.15010423 0.05285902]]


In [1]:
import numpy as np

an_array = np.array([[11, 12, 13, 14],
                    [21, 22, 23, 24],
                    [31, 32, 33, 34],
                    [41, 42, 43, 44]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [3]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [4]:
print('before:', an_array[0, 1])
a_slice[0, 0] = 1000
print('after:', an_array[0, 1])

before: 12
after: 1000


In [5]:
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[1000   13]
 [  22   23]]


In [6]:
print('before:', an_array[0, 1])
a_slice[0, 0] = 2000
print('after:', an_array[0, 1])

before: 1000
after: 1000


In [7]:
an_array = np.array([[11, 12, 13, 14],
                    [21, 22, 23, 24],
                    [31, 32, 33, 34],
                    [41, 42, 43, 44]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [9]:
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [10]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [11]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)

[12 22 32 42] (4,)

[[12]
 [22]
 [32]
 [42]] (4, 1)


In [12]:
an_array = np.array([[11, 12, 13, 14],
                    [21, 22, 23, 24],
                    [31, 32, 33, 34],
                    [41, 42, 43, 44]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [16]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked ： ',  row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked ：  [0 1 2 3]


In [17]:
for row, col in zip(row_indices, col_indices):
    print(row, ',', col)

0 , 0
1 , 1
2 , 2
3 , 0


In [18]:
print('values in the array at those indices:', an_array[row_indices, col_indices])

values in the array at those indices: [11 22 33 41]


In [19]:
an_array[row_indices, col_indices] += 10000

print('\nchanged array:')
print(an_array)


changed array:
[[10011    12    13    14]
 [   21 10022    23    24]
 [   31    32 10033    34]
 [10041    42    43    44]]


# Boolean Indexing

In [2]:
import numpy as np
# create a 3 x 2 array
an_array = np.array([[11, 12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [4]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [6]:
print(an_array[filter])

[21 22 31 32]


In [7]:
an_array[an_array > 15]

array([21, 22, 31, 32])

In [10]:
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22])

In [13]:
an_array[(an_array % 2 ) == 0] += 100
print(an_array)

[[ 11 212]
 [ 21 222]
 [ 31 232]]


# Data types and array operation

In [17]:
import numpy as np
ex1 = np.array([11, 12])
print(ex1.dtype)

int32


In [19]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


In [23]:
ex3 = np.array([11, 12], dtype=np.int64)
print(ex3.dtype)

int64


In [24]:
ex4 = np.array([11.0, 12.0], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [25]:
ex5 = np.array([11.0, 12.0], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 12.]


# Arithmetic Array Operations

In [26]:
x = np.array([[111, 112], [121, 122]], dtype=np.int)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [27]:
print(x+y)
print()
print(np.add(x, y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [28]:
print(x-y)

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [29]:
print(x*y)
print(x/y)

[[23432.1 23755.2]
 [26753.1 27096.2]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [30]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [32]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]
