In [1]:
import numpy as np

In [2]:
arr = 10 * np.random.randn(2, 5)
print(arr)

[[ 12.83586165  13.94533605   4.19452491 -18.12381861  -2.20173093]
 [ -5.71452243  -2.06580751  -0.23978063  -5.04625786   6.39321126]]


In [3]:
print(arr.mean())

0.3977015914264599


In [4]:
print(arr.mean(axis = 1))

[ 2.13003461 -1.33463143]


In [5]:
print(arr.mean(axis = 0))

[  3.56066961   5.93976427   1.97737214 -11.58503823   2.09574016]


In [6]:
print(arr.sum())

3.977015914264599


In [8]:
print(np.median(arr, axis = 1))

[ 4.19452491 -2.06580751]


# Sorting

In [10]:
unsorted = np.random.randn(10)
print(unsorted)

[-0.02095317  0.45000119 -1.50273844 -0.00925812  0.57793891 -1.68211234
  0.65104179 -0.75758557  1.28232781  0.07283858]


In [11]:
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.68211234 -1.50273844 -0.75758557 -0.02095317 -0.00925812  0.07283858
  0.45000119  0.57793891  0.65104179  1.28232781]

[-0.02095317  0.45000119 -1.50273844 -0.00925812  0.57793891 -1.68211234
  0.65104179 -0.75758557  1.28232781  0.07283858]


In [12]:
array = np.array([1, 2, 1, 4, 2, 1, 4, 2])
print(np.unique(array))

[1 2 4]


In [13]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [14]:
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [15]:
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [16]:
print(np.setdiff1d(s1, s2))

['desk']


In [18]:
print(np.in1d(s1, s2))

[False  True  True]
